#!/usr/bin/env python3
"""
One-command setup script for CBB Edge Analyzer
Automates environment setup, dependency installation, and database initialization
"""

import os
import sys
import subprocess
import secrets
from pathlib import Path


def print_header(text):
    """Print formatted header"""
    print("\n" + "="*80)
    print(f"  {text}")
    print("="*80 + "\n")


def run_command(cmd, description, check=True):
    """Run shell command with nice output"""
    print(f"⚙️  {description}...")
    try:
        result = subprocess.run(
            cmd,
            shell=True,
            check=check,
            capture_output=True,
            text=True
        )
        if result.returncode == 0:
            print(f"✅ {description} - Success")
            return True
        else:
            print(f"❌ {description} - Failed")
            if result.stderr:
                print(f"   Error: {result.stderr[:200]}")
            return False
    except Exception as e:
        print(f"❌ {description} - Error: {e}")
        return False


def generate_api_key():
    """Generate secure random API key"""
    return secrets.token_urlsafe(32)


def create_env_file():
    """Create .env file with prompts"""
    print_header("Environment Configuration")
    
    if os.path.exists('.env'):
        response = input("⚠️  .env file already exists. Overwrite? (y/N): ")
        if response.lower() != 'y':
            print("Keeping existing .env file")
            return True
    
    print("\nYou'll need:")
    print("1. The Odds API key (free tier: https://the-odds-api.com)")
    print("2. KenPom API key ($95/year: https://kenpom.com/api)")
    print("3. PostgreSQL database URL (or use local Docker)")
    
    print("\n" + "-"*80)
    
    # Get API keys
    odds_key = input("\nThe Odds API Key (or press Enter to skip): ").strip()
    kenpom_key = input("KenPom API Key (or press Enter to skip): ").strip()
    
    # Database
    print("\n📦 Database Setup:")
    print("1. Use local Docker (will start PostgreSQL container)")
    print("2. Use Railway/Supabase (enter connection string)")
    print("3. Skip (configure manually later)")
    
    db_choice = input("\nChoice (1/2/3): ").strip()
    
    if db_choice == "1":
        # Start local PostgreSQL via Docker
        print("\n🐳 Starting PostgreSQL container...")
        db_password = secrets.token_urlsafe(16)
        
        docker_cmd = f"""
        docker run -d \
            --name cbb-postgres \
            -e POSTGRES_PASSWORD={db_password} \
            -e POSTGRES_DB=cbb_edge \
            -p 5432:5432 \
            postgres:15
        """
        
        if run_command(docker_cmd.strip(), "Start PostgreSQL container", check=False):
            database_url = f"postgresql://postgres:{db_password}@localhost:5432/cbb_edge"
            print(f"\n✅ PostgreSQL running on port 5432")
            print(f"   Password: {db_password}")
        else:
            print("\n⚠️  Docker not found or failed. Install Docker or choose option 2.")
            database_url = ""
    
    elif db_choice == "2":
        database_url = input("\nPostgreSQL connection string: ").strip()
    
    else:
        database_url = "postgresql://user:pass@localhost:5432/cbb_edge"
        print("\n⚠️  Using placeholder DATABASE_URL. Update .env before running!")
    
    # Generate API key
    api_key = generate_api_key()
    
    # Write .env file
    env_content = f"""# CBB Edge Analyzer Configuration
# Generated by setup.py

# Database
DATABASE_URL={database_url}

# API Keys (REQUIRED for production)
THE_ODDS_API_KEY={odds_key if odds_key else 'your_odds_api_key_here'}
KENPOM_API_KEY={kenpom_key if kenpom_key else 'your_kenpom_api_key_here'}

# Authentication
API_KEY_USER1={api_key}

# Optional: Additional users
# API_KEY_USER2=

# Optional: Alerts
# TWILIO_ACCOUNT_SID=
# TWILIO_AUTH_TOKEN=
# TWILIO_FROM_NUMBER=
# TWILIO_TO_NUMBER=
# SENDGRID_API_KEY=
# ALERT_EMAIL=

# App Configuration
ENVIRONMENT=development
LOG_LEVEL=INFO
NIGHTLY_CRON_HOUR=3
NIGHTLY_CRON_TIMEZONE=America/New_York

# Model Parameters
BASE_SD=11.0
WEIGHT_KENPOM=0.342
WEIGHT_BARTTORVIK=0.333
WEIGHT_EVANMIYA=0.325
HOME_ADVANTAGE=3.09

# Betting Parameters
MAX_KELLY_FRACTION=0.20
FRACTIONAL_KELLY_DIVISOR=2
MAX_BANKROLL_PCT_PER_BET=1.5
STARTING_BANKROLL=1000
"""
    
    with open('.env', 'w') as f:
        f.write(env_content)
    
    print(f"\n✅ .env file created")
    print(f"\n🔑 Your API key (save this!): {api_key}")
    print(f"\n⚠️  Update .env with your Odds API and KenPom keys before running!")
    
    return True


def setup_venv():
    """Create virtual environment"""
    print_header("Virtual Environment Setup")
    
    if os.path.exists('venv'):
        print("✅ Virtual environment already exists")
        return True
    
    python_cmd = sys.executable
    return run_command(f"{python_cmd} -m venv venv", "Create virtual environment")


def install_dependencies():
    """Install Python dependencies"""
    print_header("Installing Dependencies")
    
    # Detect OS
    if os.name == 'nt':  # Windows
        pip_cmd = "venv\\Scripts\\pip"
    else:  # Unix
        pip_cmd = "venv/bin/pip"
    
    # Upgrade pip
    run_command(f"{pip_cmd} install --upgrade pip", "Upgrade pip")
    
    # Install requirements
    if os.path.exists('requirements.txt'):
        return run_command(
            f"{pip_cmd} install -r requirements.txt",
            "Install Python packages (this may take 2-3 minutes)"
        )
    else:
        print("❌ requirements.txt not found")
        return False


def init_database():
    """Initialize database schema"""
    print_header("Database Initialization")
    
    response = input("\nInitialize database now? (Y/n): ")
    if response.lower() == 'n':
        print("⏭️  Skipping database initialization")
        return True
    
    # Detect OS
    if os.name == 'nt':
        python_cmd = "venv\\Scripts\\python"
    else:
        python_cmd = "venv/bin/python"
    
    return run_command(
        f"{python_cmd} scripts/init_db.py --seed",
        "Initialize database schema"
    )


def run_tests():
    """Run test suite"""
    print_header("Running Tests")
    
    response = input("\nRun test suite? (Y/n): ")
    if response.lower() == 'n':
        print("⏭️  Skipping tests")
        return True
    
    if os.name == 'nt':
        pytest_cmd = "venv\\Scripts\\pytest"
    else:
        pytest_cmd = "venv/bin/pytest"
    
    return run_command(
        f"{pytest_cmd} tests/ -v",
        "Run unit tests"
    )


def print_next_steps():
    """Print what to do next"""
    print_header("🎉 Setup Complete!")
    
    print("Next steps:\n")
    
    print("1. Activate virtual environment:")
    if os.name == 'nt':
        print("   venv\\Scripts\\activate")
    else:
        print("   source venv/bin/activate")
    
    print("\n2. Update .env with your API keys:")
    print("   nano .env  # or your favorite editor")
    
    print("\n3. Start the backend:")
    print("   uvicorn backend.main:app --reload")
    
    print("\n4. Start the dashboard (in new terminal):")
    print("   streamlit run dashboard/app.py")
    
    print("\n5. Visit:")
    print("   API: http://localhost:8000")
    print("   Dashboard: http://localhost:8501")
    
    print("\n" + "-"*80)
    print("\n📚 Documentation:")
    print("   README.md - Full overview")
    print("   QUICKSTART.md - Deployment guide")
    print("   IMPLEMENTATION.md - Development roadmap")
    
    print("\n🚀 Deploy to production:")
    print("   Follow QUICKSTART.md → Railway section")
    
    print("\n" + "="*80 + "\n")


def main():
    """Main setup workflow"""
    print("""
    ╔════════════════════════════════════════════════════════════════╗
    ║                                                                ║
    ║           CBB Edge Analyzer - Automated Setup                 ║
    ║                      Version 7.0                               ║
    ║                                                                ║
    ╚════════════════════════════════════════════════════════════════╝
    """)
    
    print("This script will:")
    print("  ✓ Create virtual environment")
    print("  ✓ Install dependencies")
    print("  ✓ Configure environment variables")
    print("  ✓ Initialize database")
    print("  ✓ Run tests")
    
    response = input("\nContinue? (Y/n): ")
    if response.lower() == 'n':
        print("Aborted.")
        return
    
    # Run setup steps
    steps = [
        (setup_venv, "Virtual environment"),
        (install_dependencies, "Dependencies"),
        (create_env_file, "Environment config"),
        (init_database, "Database"),
        (run_tests, "Tests"),
    ]
    
    for step_func, step_name in steps:
        if not step_func():
            print(f"\n❌ Setup failed at: {step_name}")
            print("Fix the error above and run setup.py again")
            return
    
    print_next_steps()


if __name__ == "__main__":
    main()
