#!/usr/bin/env python3
"""
Windows-compatible setup script for CBB Edge Analyzer
Fixes path separator issues on Windows (Git Bash/MINGW64)
"""

import os
import sys
import subprocess
import secrets
from pathlib import Path
import platform


def print_header(text):
    """Print formatted header"""
    print("\n" + "="*80)
    print(f"  {text}")
    print("="*80 + "\n")


def run_command(cmd, description, check=True):
    """Run shell command with Windows compatibility"""
    print(f"⚙️  {description}...")
    
    # Detect OS and adjust command
    is_windows = platform.system() == 'Windows' or os.name == 'nt'
    
    if is_windows:
        # Use Python executable directly instead of Scripts path
        python_exe = sys.executable
        
        # Replace venv\Scripts\python with actual python path
        cmd = cmd.replace('venv\\Scripts\\python', python_exe)
        cmd = cmd.replace('venv/bin/python', python_exe)
        
        # Replace venv\Scripts\pip with python -m pip
        if 'pip' in cmd:
            cmd = cmd.replace('venv\\Scripts\\pip', f'"{python_exe}" -m pip')
            cmd = cmd.replace('venv/bin/pip', f'"{python_exe}" -m pip')
        
        # Replace venv\Scripts\pytest with python -m pytest
        if 'pytest' in cmd:
            cmd = cmd.replace('venv\\Scripts\\pytest', f'"{python_exe}" -m pytest')
            cmd = cmd.replace('venv/bin/pytest', f'"{python_exe}" -m pytest')
    
    try:
        result = subprocess.run(
            cmd,
            shell=True,
            check=check,
            capture_output=True,
            text=True
        )
        if result.returncode == 0:
            print(f"✅ {description} - Success")
            return True
        else:
            print(f"❌ {description} - Failed")
            if result.stderr:
                print(f"   Error: {result.stderr[:500]}")
            return False
    except Exception as e:
        print(f"❌ {description} - Error: {e}")
        return False


def generate_api_key():
    """Generate secure random API key"""
    return secrets.token_urlsafe(32)


def create_env_file():
    """Create .env file with prompts"""
    print_header("Environment Configuration")
    
    if os.path.exists('.env'):
        response = input("⚠️  .env file already exists. Overwrite? (y/N): ")
        if response.lower() != 'y':
            print("Keeping existing .env file")
            return True
    
    print("\nYou'll need:")
    print("1. The Odds API key (free tier: https://the-odds-api.com)")
    print("2. KenPom API key ($95/year: https://kenpom.com/api)")
    print("3. PostgreSQL database URL (or use local Docker)")
    
    print("\n" + "-"*80)
    
    # Get API keys
    odds_key = input("\nThe Odds API Key (or press Enter to skip): ").strip()
    kenpom_key = input("KenPom API Key (or press Enter to skip): ").strip()
    
    # Database
    print("\n📦 Database Setup:")
    print("1. Use local Docker (will start PostgreSQL container)")
    print("2. Use Railway/Supabase (enter connection string)")
    print("3. Skip (configure manually later)")
    
    db_choice = input("\nChoice (1/2/3): ").strip()
    
    if db_choice == "1":
        # Start local PostgreSQL via Docker
        print("\n🐳 Starting PostgreSQL container...")
        db_password = secrets.token_urlsafe(16)
        
        docker_cmd = f'docker run -d --name cbb-postgres -e POSTGRES_PASSWORD={db_password} -e POSTGRES_DB=cbb_edge -p 5432:5432 postgres:15'
        
        if run_command(docker_cmd, "Start PostgreSQL container", check=False):
            database_url = f"postgresql://postgres:{db_password}@localhost:5432/cbb_edge"
            print(f"\n✅ PostgreSQL running on port 5432")
            print(f"   Password: {db_password}")
        else:
            print("\n⚠️  Docker not found or failed. Install Docker or choose option 2.")
            database_url = ""
    
    elif db_choice == "2":
        database_url = input("\nPostgreSQL connection string: ").strip()
    
    else:
        database_url = "postgresql://user:pass@localhost:5432/cbb_edge"
        print("\n⚠️  Using placeholder DATABASE_URL. Update .env before running!")
    
    # Generate API key
    api_key = generate_api_key()
    
    # Write .env file
    env_content = f"""# CBB Edge Analyzer Configuration
# Generated by setup.py

# Database
DATABASE_URL={database_url}

# API Keys (REQUIRED for production)
THE_ODDS_API_KEY={odds_key if odds_key else 'your_odds_api_key_here'}
KENPOM_API_KEY={kenpom_key if kenpom_key else 'your_kenpom_api_key_here'}

# Authentication
API_KEY_USER1={api_key}

# App Configuration
ENVIRONMENT=development
LOG_LEVEL=INFO
NIGHTLY_CRON_HOUR=3
NIGHTLY_CRON_TIMEZONE=America/New_York

# Model Parameters
BASE_SD=11.0
WEIGHT_KENPOM=0.342
WEIGHT_BARTTORVIK=0.333
WEIGHT_EVANMIYA=0.325
HOME_ADVANTAGE=3.09
"""
    
    with open('.env', 'w') as f:
        f.write(env_content)
    
    print(f"\n✅ .env file created")
    print(f"\n🔑 Your API key (save this!): {api_key}")
    
    if not odds_key or not kenpom_key:
        print(f"\n⚠️  Update .env with your Odds API and KenPom keys before running!")
    
    return True


def setup_venv():
    """Create virtual environment"""
    print_header("Virtual Environment Setup")
    
    if os.path.exists('venv'):
        print("✅ Virtual environment already exists")
        return True
    
    python_cmd = sys.executable
    return run_command(f'"{python_cmd}" -m venv venv', "Create virtual environment")


def install_dependencies():
    """Install Python dependencies"""
    print_header("Installing Dependencies")
    
    python_exe = sys.executable
    
    # Upgrade pip
    run_command(f'"{python_exe}" -m pip install --upgrade pip', "Upgrade pip")
    
    # Install requirements
    if os.path.exists('requirements.txt'):
        return run_command(
            f'"{python_exe}" -m pip install -r requirements.txt',
            "Install Python packages (this may take 2-3 minutes)"
        )
    else:
        print("❌ requirements.txt not found")
        return False


def init_database():
    """Initialize database schema"""
    print_header("Database Initialization")
    
    response = input("\nInitialize database now? (Y/n): ")
    if response.lower() == 'n':
        print("⏭️  Skipping database initialization")
        return True
    
    python_exe = sys.executable
    
    return run_command(
        f'"{python_exe}" scripts/init_db.py --seed',
        "Initialize database schema"
    )


def run_tests():
    """Run test suite"""
    print_header("Running Tests")
    
    response = input("\nRun test suite? (Y/n): ")
    if response.lower() == 'n':
        print("⏭️  Skipping tests")
        return True
    
    python_exe = sys.executable
    
    return run_command(
        f'"{python_exe}" -m pytest tests/ -v',
        "Run unit tests"
    )


def print_next_steps():
    """Print what to do next"""
    print_header("🎉 Setup Complete!")
    
    print("Next steps:\n")
    
    print("1. Your virtual environment is already activated!")
    print("   (Python path: {})".format(sys.executable))
    
    print("\n2. Update .env with your API keys if you skipped them:")
    print("   notepad .env  # or your favorite editor")
    
    print("\n3. Start the backend:")
    print("   python -m uvicorn backend.main:app --reload")
    
    print("\n4. Start the dashboard (in new Git Bash window):")
    print("   cd ~/repos/v1/cbb-edge")
    print("   source venv/Scripts/activate  # Windows Git Bash")
    print("   python -m streamlit run dashboard/app.py")
    
    print("\n5. Visit:")
    print("   API: http://localhost:8000")
    print("   Dashboard: http://localhost:8501")
    
    print("\n" + "-"*80)
    print("\n📚 Documentation:")
    print("   README.md - Full overview")
    print("   QUICKSTART.md - Deployment guide")
    print("   IMPLEMENTATION.md - Development roadmap")
    
    print("\n" + "="*80 + "\n")


def main():
    """Main setup workflow"""
    print("""
    ╔════════════════════════════════════════════════════════════════╗
    ║                                                                ║
    ║           CBB Edge Analyzer - Automated Setup                 ║
    ║                Version 7.0 - Windows Compatible                ║
    ║                                                                ║
    ╚════════════════════════════════════════════════════════════════╝
    """)
    
    print("Detected OS: {}".format(platform.system()))
    print("Python: {}".format(sys.executable))
    
    print("\nThis script will:")
    print("  ✓ Create virtual environment")
    print("  ✓ Install dependencies")
    print("  ✓ Configure environment variables")
    print("  ✓ Initialize database")
    print("  ✓ Run tests")
    
    response = input("\nContinue? (Y/n): ")
    if response.lower() == 'n':
        print("Aborted.")
        return
    
    # Run setup steps
    steps = [
        (setup_venv, "Virtual environment"),
        (install_dependencies, "Dependencies"),
        (create_env_file, "Environment config"),
        (init_database, "Database"),
        (run_tests, "Tests"),
    ]
    
    for step_func, step_name in steps:
        if not step_func():
            print(f"\n❌ Setup failed at: {step_name}")
            print("Fix the error above and run setup.py again")
            return
    
    print_next_steps()


if __name__ == "__main__":
    main()
